version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8.8
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: python -m unittest

workflows:
  main:
    jobs:
      - test
